// =============================================================================
// End-to-end tests for the ONE MATRIX PDF engine.
//
// These render real PDFs, then read the generated bytes back — inflating the
// content streams and decoding both the /ActualText spans and the /ToUnicode
// CMaps — to prove the text is genuinely there. The bug these guard against is
// a PDF that opens but is blank or garbled, which no "did it not throw?" test
// would catch.
// =============================================================================

import { describe, expect, it } from "vitest";
import { renderPdf, splitRuns } from "../src/lib/pdf/engine";
import { markdownToBlocks, renderCertificatePdf, renderDocumentPdf } from "../src/lib/pdf/documents";
import { FACE_NAMES, faceForChar, faceSupports, fontBytes } from "../src/lib/pdf/fonts";
import { extractDrawnCodepoints, extractPdfText, mediaBoxes, pageCount } from "./helpers/pdf-text";

// The exact strings from the bug report.
const ENGLISH = "Matrix AI Platform";
const BANGLA = "আমি বাংলায় পরীক্ষা করছি। এটি Matrix AI-এর একটি পরীক্ষা।";
const MIXED = "Matrix AI — বাংলা পরীক্ষা — 100% Complete";
const SYMBOLS = "✓ Success • → Export • #Matrix";

describe("embedded fonts", () => {
  it("ships real TrueType files for every registered face", () => {
    for (const face of FACE_NAMES) {
      const bytes = fontBytes(face);
      expect(bytes.byteLength).toBeGreaterThan(50_000);
      // TrueType (0x00010000) or a version tag — never an HTML error page.
      const tag = bytes.readUInt32BE(0);
      expect([0x00010000, 0x74727565, 0x4f54544f]).toContain(tag);
    }
  });

  it("covers Latin, Bangla and the symbol set across the family", () => {
    for (const char of `${ENGLISH}${BANGLA}${MIXED}${SYMBOLS}`) {
      if (char === " ") continue;
      expect(faceForChar(char, "sans", "regular"), `no face for ${JSON.stringify(char)}`).not.toBeNull();
    }
  });

  it("routes Bangla to the Bengali face and Latin to the sans face", () => {
    expect(faceForChar("অ", "sans", "regular")).toBe("bengali");
    expect(faceForChar("A", "sans", "regular")).toBe("sans");
    expect(faceForChar("A", "mono", "regular")).toBe("mono");
    expect(faceForChar("অ", "sans", "bold")).toBe("bengali-bold");
    // Symbols the Bengali face lacks still resolve, via the sans fallback.
    expect(faceForChar("✓", "sans", "regular")).toBe("sans");
    expect(faceSupports("sans", "→".codePointAt(0)!)).toBe(true);
  });
});

describe("run splitting", () => {
  it("splits mixed text into runs each face can actually draw", () => {
    const runs = splitRuns(MIXED, "sans", "regular");
    expect(runs.length).toBeGreaterThan(1);
    expect(runs.map((r) => r.text).join("")).toBe(MIXED);
    expect(new Set(runs.map((r) => r.face))).toContain("bengali");
    expect(new Set(runs.map((r) => r.face))).toContain("sans");
  });

  it("keeps Bangla combining marks with their base consonant", () => {
    // পরীক্ষা mixes consonants, vowel signs and a virama conjunct.
    const runs = splitRuns("পরীক্ষা", "sans", "regular");
    expect(runs).toHaveLength(1);
    expect(runs[0].face).toBe("bengali");
  });

  it("never silently drops a character", () => {
    const runs = splitRuns(`${ENGLISH} ${BANGLA} ${SYMBOLS}`, "sans", "regular");
    const joined = runs.map((r) => r.text).join("");
    expect(joined).toBe(`${ENGLISH} ${BANGLA} ${SYMBOLS}`);
  });

  it("marks a truly unsupported character visibly instead of deleting it", () => {
    // A private-use codepoint no font covers.
    const runs = splitRuns("A\uE123B", "sans", "regular");
    const joined = runs.map((r) => r.text).join("");
    expect(joined).toHaveLength(3);
    expect(joined).toContain("\u25A1");
    expect(joined).not.toBe("AB");
  });
});

describe("document PDFs contain the text they were given", () => {
  it("renders each required test string, extractably", async () => {
    for (const sample of [ENGLISH, BANGLA, MIXED, SYMBOLS]) {
      const bytes = await renderDocumentPdf(sample, { title: "Unicode test" });
      const text = await extractPdfText(bytes);
      expect(text, `missing from PDF: ${sample}`).toContain(sample);
    }
  });

  it("renders all four together in one document", async () => {
    const source = `# ${ENGLISH}\n\n${BANGLA}\n\n${MIXED}\n\n${SYMBOLS}\n`;
    const bytes = await renderDocumentPdf(source, { title: ENGLISH });
    const text = await extractPdfText(bytes);
    for (const sample of [ENGLISH, BANGLA, MIXED, SYMBOLS]) expect(text).toContain(sample);
  });

  it("embeds the glyphs it draws, so the page is not blank", async () => {
    const bytes = await renderDocumentPdf(`${BANGLA}\n\n${SYMBOLS}`, { title: "Glyphs" });
    const drawn = extractDrawnCodepoints(bytes);
    // Distinctive characters from each script must be present as real glyphs.
    for (const char of ["আ", "ব", "ল", "✓", "→", "•"]) {
      expect(drawn.has(char), `glyph not embedded: ${char}`).toBe(true);
    }
    // A blank page would be a few KB; a real one carries font subsets.
    expect(bytes.byteLength).toBeGreaterThan(10_000);
  });

  it("never turns unsupported characters into empty parentheses", async () => {
    const bytes = await renderDocumentPdf(`${BANGLA}\n${SYMBOLS}`, { title: "No placeholders" });
    const text = await extractPdfText(bytes);
    expect(text).not.toMatch(/\(\s*\)/);
    expect(text).not.toContain("?????");
    expect(text).not.toContain("\u25A1");
  });

  it("keeps numbers, punctuation and currency intact", async () => {
    const sample = "0123456789 — 100% · @ # $ % & * € ₹ © ✓ → \"quotes\" 'apostrophe'";
    const text = await extractPdfText(await renderDocumentPdf(sample, { title: "Symbols" }));
    for (const token of ["0123456789", "100%", "€", "₹", "©", "✓", "→"]) expect(text).toContain(token);
  });

  it("paginates long content instead of overflowing one page", async () => {
    const long = Array.from({ length: 300 }, (_, i) => `Line ${i}: ${BANGLA}`).join("\n\n");
    const bytes = await renderDocumentPdf(long, { title: "Long report" });
    expect(pageCount(bytes)).toBeGreaterThan(1);
    const text = await extractPdfText(bytes);
    expect(text).toContain("Line 0:");
    expect(text).toContain("Line 299:");
  });

  it("uses A4 portrait pages", async () => {
    const boxes = mediaBoxes(await renderDocumentPdf(ENGLISH, { title: ENGLISH }));
    expect(boxes.length).toBeGreaterThan(0);
    for (const [w, h] of boxes) {
      expect(Math.round(w)).toBe(595);
      expect(Math.round(h)).toBe(842);
    }
  });

  it("preserves headings, bullets and code blocks", async () => {
    const source = "# Heading\n\n- first bullet\n- ✓ second bullet\n\n1. numbered\n\n```py\nprint(\"hi\")\n```\n";
    const text = await extractPdfText(await renderDocumentPdf(source, { title: "Structure" }));
    expect(text).toContain("Heading");
    expect(text).toContain("first bullet");
    expect(text).toContain("✓ second bullet");
    expect(text).toContain("numbered");
    expect(text).toContain('print("hi")');
  });
});

describe("markdown to blocks", () => {
  it("recognises the structures a chat reply uses", () => {
    const blocks = markdownToBlocks("# H1\n## H2\n\ntext\n\n- bullet\n\n1. item\n\n> quote\n\n```\ncode\n```");
    const texts = blocks.filter((b) => b.type === "text").map((b) => (b as { text: string }).text);
    expect(texts).toContain("H1");
    expect(texts).toContain("H2");
    expect(texts).toContain("text");
    expect(texts.some((t) => t.startsWith("•"))).toBe(true);
    expect(texts.some((t) => t.startsWith("1."))).toBe(true);
    expect(texts).toContain("quote");
    expect(texts).toContain("code");
  });

  it("keeps Bangla untouched while stripping Markdown syntax", () => {
    const blocks = markdownToBlocks(`**${BANGLA}**`);
    expect((blocks[0] as { text: string }).text).toBe(BANGLA);
  });
});

describe("certificate PDF end to end", () => {
  const CERT = {
    certificate_id: "MTRX-CERT-TEST-001",
    course: "Python Fundamentals",
    display_name: "Test User",
    score_percent: 100,
    issued_at: "2026-09-05T10:00:00.000Z",
    issued_by: "MATRIX — THAMJJ13.TOP White Hat Team",
  };

  it("contains every field from the certificate test case", async () => {
    const text = await extractPdfText(await renderCertificatePdf(CERT));
    expect(text).toContain("CERTIFICATE OF COMPLETION");
    expect(text).toContain("Test User");
    expect(text).toContain("Python Fundamentals");
    expect(text).toContain("100%");
    expect(text).toContain("MTRX-CERT-TEST-001");
  });

  it("is exactly one A4 landscape page", async () => {
    const bytes = await renderCertificatePdf(CERT);
    expect(pageCount(bytes)).toBe(1);
    expect(mediaBoxes(bytes)).toEqual([[842, 595]]);
  });

  it("contains only certificate content — no navigation or chat UI", async () => {
    const text = await extractPdfText(await renderCertificatePdf(CERT));
    for (const chrome of ["Dashboard", "Sidebar", "Send a message", "New chat", "Settings", "Scanner"]) {
      expect(text).not.toContain(chrome);
    }
  });

  it("renders a Bangla name and course", async () => {
    const text = await extractPdfText(
      await renderCertificatePdf({ ...CERT, display_name: "রাফিদ হাসান", course: "সাইবার নিরাপত্তা মৌলিক" }),
    );
    expect(text).toContain("রাফিদ হাসান");
    expect(text).toContain("সাইবার নিরাপত্তা মৌলিক");
  });

  it("is never a blank page", async () => {
    const bytes = await renderCertificatePdf(CERT);
    expect(bytes.byteLength).toBeGreaterThan(10_000);
    expect((await extractPdfText(bytes)).replace(/\s+/g, "").length).toBeGreaterThan(80);
  });
});

describe("engine primitives", () => {
  it("honours explicit page sizes and page breaks", async () => {
    const bytes = await renderPdf({
      title: "Sizing",
      size: [400, 300],
      blocks: [{ type: "text", text: "one" }, { type: "page-break" }, { type: "text", text: "two" }],
    });
    expect(pageCount(bytes)).toBe(2);
    expect(mediaBoxes(bytes)[0]).toEqual([400, 300]);
    const text = await extractPdfText(bytes);
    expect(text).toContain("one");
    expect(text).toContain("two");
  });

  it("resolves with complete bytes, ending at %%EOF", async () => {
    const bytes = await renderPdf({ title: "Complete", blocks: [{ type: "text", text: BANGLA }] });
    const raw = Buffer.from(bytes).toString("latin1");
    expect(raw.startsWith("%PDF-")).toBe(true);
    expect(raw.trimEnd().endsWith("%%EOF")).toBe(true);
  });

  it("centres and right-aligns using the same measurement it draws with", async () => {
    const bytes = await renderPdf({
      title: "Aligned",
      blocks: [
        { type: "text", text: MIXED, align: "center" },
        { type: "text", text: MIXED, align: "right" },
      ],
    });
    const text = await extractPdfText(bytes);
    expect((text.match(/100% Complete/g) ?? []).length).toBe(2);
  });
});
