-- =============================================================================
-- MATRIX AI — 0007: Seed data
-- Countries, admin RBAC, scam categories & articles, verified reporting
-- resources, 7 courses with modules/lessons/quizzes, RAG knowledge chunks.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Countries (consent rules are configurable per country)
-- ---------------------------------------------------------------------------
insert into public.countries (id, name, consent_required, consent_min_age, reporting_note) values
  ('US', 'United States', true, 13, 'Report to FTC at reportfraud.ftc.gov'),
  ('GB', 'United Kingdom', true, 13, 'Report to Action Fraud'),
  ('AU', 'Australia', true, 13, 'Report to Scamwatch / eSafety Commissioner'),
  ('CA', 'Canada', true, 13, 'Report to the Canadian Anti-Fraud Centre'),
  ('BD', 'Bangladesh', true, 13, 'Report to the Digital Security Agency (DSA)'),
  ('IN', 'India', true, 13, 'Report to CERT-In / cybercrime.gov.in'),
  ('PK', 'Pakistan', true, 13, 'Report to the National Cyber Crime Reporting Center'),
  ('SG', 'Singapore', true, 13, 'Report to the Cyber Security Agency (CSA)'),
  ('MY', 'Malaysia', true, 13, 'Report to CyberSecurity Malaysia'),
  ('PH', 'Philippines', true, 13, 'Report to the NBI Cybercrime Division'),
  ('ID', 'Indonesia', true, 13, 'Report to patrolsiaga.id'),
  ('NZ', 'New Zealand', true, 13, 'Report to CERT NZ / Netsafe'),
  ('IE', 'Ireland', true, 13, 'Report to garda.ie / FraudSMART'),
  ('DE', 'Germany', true, 16, 'Report to the BSI / local police'),
  ('NL', 'Netherlands', true, 16, 'Report to politie.nl / Fraudehelpdesk'),
  ('AE', 'United Arab Emirates', true, 13, 'Report to eCrime.ae'),
  ('BR', 'Brazil', true, 13, 'Report to gov.br / delegacia virtual'),
  ('ZA', 'South Africa', true, 13, 'Report to SAPS / the SAPS cybercrime unit'),
  ('NG', 'Nigeria', true, 13, 'Report to the EFCC / NCC')
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- Admin RBAC roles & permissions
-- ---------------------------------------------------------------------------
insert into public.admin_permissions (code, description) values
  ('admin.manage',      'Assign and remove admin roles'),
  ('users.view',        'View user accounts (non-PII fields)'),
  ('users.view_pii',    'View PII fields such as address and phone'),
  ('verification.review','Review identity/age verification submissions'),
  ('consent.review',    'Review guardian consent submissions'),
  ('content.manage',    'Manage scam library, courses, resources'),
  ('reports.view',      'View and update scam reports'),
  ('security.view',     'View security events and sessions'),
  ('ai.view',           'View AI usage and safety logs'),
  ('learning.view',     'View quiz attempts and course progress'),
  ('certificates.view', 'View issued certificates'),
  ('audit.view',        'View audit logs'),
  ('privacy.access',    'Request time-limited access to user conversations'),
  ('system.settings',   'Manage system settings')
on conflict (code) do nothing;

insert into public.admin_roles (name, description) values
  ('super_admin',   'Full platform access'),
  ('security_admin','Security operations: verification, consent, events, reports'),
  ('content_admin', 'Content: scam library, courses, resources'),
  ('support_admin', 'Support: user lookups and report triage'),
  ('auditor',       'Read-only audit and AI-safety access')
on conflict (name) do nothing;

insert into public.admin_role_permissions (role_id, permission_id)
select r.id, p.id
from (values
  ('super_admin',   'admin.manage'),
  ('super_admin',   'users.view'),
  ('super_admin',   'users.view_pii'),
  ('super_admin',   'verification.review'),
  ('super_admin',   'consent.review'),
  ('super_admin',   'content.manage'),
  ('super_admin',   'reports.view'),
  ('super_admin',   'security.view'),
  ('super_admin',   'ai.view'),
  ('super_admin',   'learning.view'),
  ('super_admin',   'certificates.view'),
  ('super_admin',   'audit.view'),
  ('super_admin',   'privacy.access'),
  ('super_admin',   'system.settings'),
  ('security_admin','users.view'),
  ('security_admin','users.view_pii'),
  ('security_admin','verification.review'),
  ('security_admin','consent.review'),
  ('security_admin','security.view'),
  ('security_admin','reports.view'),
  ('security_admin','ai.view'),
  ('security_admin','certificates.view'),
  ('security_admin','audit.view'),
  ('security_admin','privacy.access'),
  ('content_admin', 'content.manage'),
  ('content_admin', 'learning.view'),
  ('content_admin', 'certificates.view'),
  ('content_admin', 'reports.view'),
  ('support_admin', 'users.view'),
  ('support_admin', 'reports.view'),
  ('support_admin', 'consent.review'),
  ('auditor',       'audit.view'),
  ('auditor',       'ai.view'),
  ('auditor',       'security.view'),
  ('auditor',       'certificates.view')
) as v(role_name, perm_code)
join public.admin_roles r on r.name = v.role_name
join public.admin_permissions p on p.code = v.perm_code
on conflict do nothing;

-- ---------------------------------------------------------------------------
-- Scam categories
-- ---------------------------------------------------------------------------
insert into public.scam_categories (slug, name, description, icon, sort_order) values
  ('phishing',        'Phishing',          'Fake messages that trick you into giving passwords, codes or money.', 'fish', 1),
  ('online-shopping', 'Online Shopping',   'Fake shops, fake sellers and goods that never arrive.', 'cart', 2),
  ('job-scams',       'Job & Income Scams', 'Too-good-to-be-true jobs, paid tasks and "earn from home" tricks.', 'briefcase', 3),
  ('tech-support',    'Tech Support',      'Fake helpers who say your device is infected and ask for money.', 'wrench', 4),
  ('prize-lottery',   'Prize & Lottery',   '"You won!" messages that ask you to pay first.', 'gift', 5),
  ('romance',         'Romance & Friendship', 'Fake friends or partners who build trust then ask for money.', 'heart', 6),
  ('investment-crypto','Investment & Crypto','Fake trading platforms and "guaranteed profit" promises.', 'chart', 7),
  ('impersonation',   'Impersonation',     'Scammers pretending to be police, banks or companies you trust.', 'mask', 8),
  ('malware',         'Malware & Fake Apps','Harmful apps and downloads that steal your data.', 'bug', 9),
  ('identity-theft',  'Identity Theft',    'Stealing your personal details to open accounts or commit fraud.', 'fingerprint', 10)
on conflict (slug) do nothing;

-- ---------------------------------------------------------------------------
-- Scam articles (trusted/official sources; verified)
-- ---------------------------------------------------------------------------
insert into public.scam_articles
  (category_id, title, slug, description, warning_signs, prevention, response_steps,
   reporting_guidance, source_name, source_url, country, trust_level, last_verified, status)
select c.id, v.title, v.slug, v.description, v.warning_signs, v.prevention, v.response_steps,
       v.reporting_guidance, v.source_name, v.source_url, v.country, v.trust_level,
       '2026-08-01'::timestamptz, 'active'
from (values
  ('phishing',
   'Spotting Phishing Messages', 'spotting-phishing-messages',
   'Phishing is when a scammer sends a fake message that looks like it is from a real company, to steal your password, code or money.',
   'Urgency ("act now!"), spelling mistakes, unknown links, asks for your password or one-time code, sender address that is slightly different from the real one.',
   'Never click links in unexpected messages. Type the website address yourself. Turn on two-factor authentication (2FA). Use a password manager.',
   'Do not click or reply. If you clicked, change your password and log out of all devices. If you shared a code, tell a trusted adult and contact the real company.',
   'Report phishing emails and texts to the official reporting organisation for your country (see reporting resources).',
   'APWG & FTC guidance', 'https://www.ftc.gov/news-events/topics/identity-theft/phishing', 'US', 'trusted_official'),
  ('online-shopping',
   'Fake Online Shops', 'fake-online-shops',
   'Scammers build realistic-looking shops with huge discounts, then take your money and send nothing.',
   'Prices far below normal, payment only by bank transfer or gift cards, no contact phone number, the shop was created days ago, reviews all look copied.',
   'Check the domain name, search "<shop name> scam" before buying, pay with a credit card or a payment service that protects buyers.',
   'Keep screenshots of everything, tell a trusted adult, report the payment to your bank, and report the shop to the official reporting organisation.',
   'Report the scam shop so others do not lose money too.',
   'FTC & Action Fraud guidance', 'https://www.actionfraud.police.uk/', 'GB', 'trusted_official'),
  ('job-scams',
   'Job and Task Scams', 'job-task-scams',
   'Fake "jobs" ask you to pay a fee first, share ID documents, or complete paid tasks that later demand your own money.',
   'Interview by chat only, salary far above normal, asks for payment or gift cards to "unlock" the job, asks for ID photos, tasks that pay you to like/rate things.',
   'Real employers never ask for money or gift cards. Never send ID documents to strangers. Talk to a trusted adult before sharing anything.',
   'Stop all contact, keep evidence, do not pay any "fee", report to the official reporting organisation and tell your parent or guardian.',
   'Report the account and the messages so the scam can be taken down.',
   'FTC job scam guidance', 'https://consumer.ftc.gov/articles/job-scams', 'US', 'trusted_official'),
  ('tech-support',
   'Fake Tech Support', 'fake-tech-support',
   'Pop-ups, calls or messages claim your device is infected and demand money to "fix" it.',
   'Sudden pop-up warnings with a phone number, caller claims to be from Microsoft or your bank, asks for remote access to your computer, wants payment in gift cards.',
   'Real companies never call you about viruses. Never give remote access to anyone you did not contact yourself. Close the pop-up (do not call the number).',
   'Tell a trusted adult, disconnect the device from the internet if you are worried, and do not pay anything.',
   'Report the call or pop-up to the official reporting organisation.',
   'FTC tech support guidance', 'https://consumer.ftc.gov/articles/tech-support-scams', 'US', 'trusted_official'),
  ('prize-lottery',
   'Prize and Lottery Scams', 'prize-lottery-scams',
   '"Congratulations, you won!" messages ask you to pay a small fee or share details to receive a prize that does not exist.',
   'You never entered the contest, you must pay to receive the prize, they ask for gift cards or bank details, the message comes from a personal account.',
   'Real prizes are never given to people who did not enter, and winners never pay fees. Ignore and delete the message.',
   'Do not send money or codes. Keep the message as evidence and tell a trusted adult.',
   'Report the message to the official reporting organisation.',
   'FTC prize scam guidance', 'https://consumer.ftc.gov/articles/prizes-sweepstakes-and-lotteries', 'US', 'trusted_official'),
  ('romance',
   'Friendship and Romance Scams', 'friendship-romance-scams',
   'Someone builds a fast online relationship, then finds a reason to ask you for money or gift cards.',
   'Refuses video calls, very fast "I love you", always has an emergency that needs money, asks you to keep it secret, wants gift cards or crypto.',
   'Never send money or gift cards to someone you have only met online. Talk to a trusted adult — real friends never ask you to keep money a secret.',
   'Stop contact, save the chat history, tell a trusted adult, and report the profile.',
   'Report the profile and messages to the platform and the official reporting organisation.',
   'FTC romance scam guidance', 'https://consumer.ftc.gov/articles/romance-scams', 'US', 'trusted_official'),
  ('investment-crypto',
   'Investment and Crypto Scams', 'investment-crypto-scams',
   'Fake trading apps show huge "profits" to convince you to deposit real money that you can never withdraw.',
   'Guaranteed profits, you must pay to withdraw, the app is not on official app stores, famous people "endorsing" it, group chats pressuring you to invest fast.',
   'There is no such thing as a guaranteed profit. Never invest money you cannot afford to lose. Check the platform against official lists of authorised firms.',
   'Do not deposit more. Screenshot everything and tell a trusted adult. Report to the official reporting organisation and the platform.',
   'Report the app or account so it can be taken down.',
   'Action Fraud investment guidance', 'https://www.actionfraud.police.uk/', 'GB', 'trusted_official'),
  ('impersonation',
   'Scammers Pretending to Be the Police or Your Bank', 'impersonation-scams',
   'Callers or messages pretend to be police, banks or government agencies and demand money, codes or personal details.',
   'Demands to act fast, asks for one-time codes or passwords, wants payment by gift cards or crypto, threatens arrest, caller ID can be faked so do not trust it.',
   'Police and banks never ask for your password or one-time code, and never ask for gift card payment. Hang up and call the real organisation using their official number.',
   'If you shared a code, tell a trusted adult immediately and contact the real bank or agency. Keep evidence and report it.',
   'Report the call to the official reporting organisation.',
   'FBI & FTC impersonation guidance', 'https://www.ic3.gov/', 'US', 'trusted_official'),
  ('malware',
   'Fake Apps and Malicious Downloads', 'fake-apps-malware',
   'Harmful apps and downloads that look legit can steal passwords, photos and personal data from your device.',
   'The app is not on the official store, asks for strange permissions (access to messages, photos), battery drains fast, lots of ads, other apps crash.',
   'Only install apps from official stores. Check the developer name and review count. Read the permission list before installing.',
   'Remove the app, run a security scan if you can, change important passwords, and tell a trusted adult.',
   'Report the app to the store and the official reporting organisation.',
   'APWG guidance', 'https://apwg.org/', 'US', 'trusted_official'),
  ('identity-theft',
   'Protecting Your Identity Online', 'protecting-your-identity',
   'Identity theft happens when someone uses your name, date of birth or photos to open accounts or commit fraud.',
   'Accounts you never opened, strange messages from platforms you never joined, someone using your photos, unexpected bills or charges.',
   'Share as little personal information as possible. Use different passwords for every account. Turn on 2FA. Never post photos of IDs or tickets online.',
   'Tell a trusted adult immediately, keep evidence, change passwords, and report to the official reporting organisation for your country.',
   'Report identity theft to the official reporting organisation.',
   'FTC identity theft guidance', 'https://www.identitytheft.gov/', 'US', 'trusted_official')
) as v(category_slug, title, slug, description, warning_signs, prevention, response_steps,
        reporting_guidance, source_name, source_url, country, trust_level)
join public.scam_categories c on c.slug = v.category_slug
on conflict (slug) do nothing;

-- ---------------------------------------------------------------------------
-- Verified reporting resources
-- ---------------------------------------------------------------------------
insert into public.reporting_resources
  (country_id, organization, category, official_url, phone, description, last_verified, status)
values
  ('US', 'FTC — ReportFraud.ftc.gov', 'scam', 'https://reportfraud.ftc.gov/', '1-877-382-4357',
   'Official US federal consumer complaint channel for scams and fraud.', '2026-08-01', 'active'),
  ('US', 'FBI Internet Crime Complaint Center (IC3)', 'cybercrime', 'https://www.ic3.gov/', '',
   'Official FBI channel for reporting internet crime in the US.', '2026-08-01', 'active'),
  ('GB', 'Action Fraud', 'scam', 'https://www.actionfraud.police.uk/', '0300 123 2040',
   'Official UK national reporting centre for fraud and cybercrime.', '2026-08-01', 'active'),
  ('AU', 'Scamwatch', 'scam', 'https://www.scamwatch.gov.au/', '',
   'Official Australian government scam reporting and advice service.', '2026-08-01', 'active'),
  ('AU', 'eSafety Commissioner', 'abuse', 'https://www.esafety.gov.au/report', '',
   'Official Australian channel for reporting online abuse and harmful content.', '2026-08-01', 'active'),
  ('CA', 'Canadian Anti-Fraud Centre', 'scam', 'https://www.antifraudcentre-centreantifraude.ca/', '1-888-495-8501',
   'Official Canadian reporting centre for fraud and cybercrime.', '2026-08-01', 'active'),
  ('BD', 'Bangladesh Digital Security Agency (DSA)', 'cybercrime', 'https://dsa.gov.bd/', '',
   'Official Bangladesh agency for digital security and cybercrime complaints.', '2026-08-01', 'active'),
  ('IN', 'Cybercrime.gov.in', 'cybercrime', 'https://cybercrime.gov.in/', '1930',
   'Official Indian portal for reporting cybercrime, including the 1930 helpline.', '2026-08-01', 'active'),
  ('IN', 'CERT-In', 'cybercrime', 'https://www.cert-in.org.in/', '',
   'Indian national Computer Emergency Response Team.', '2026-08-01', 'active'),
  ('SG', 'Cyber Security Agency of Singapore (CSA)', 'cybercrime', 'https://www.csa.gov.sg/', '',
   'Official Singapore agency for cybersecurity incidents and advice.', '2026-08-01', 'active'),
  ('NZ', 'Netsafe', 'abuse', 'https://www.netsafe.org.nz/report/', '0508 638 723',
   'Official New Zealand online safety reporting service.', '2026-08-01', 'active'),
  ('NZ', 'CERT NZ', 'cybercrime', 'https://www.cert.govt.nz/', '',
   'Official New Zealand incident reporting centre for cyber security.', '2026-08-01', 'active'),
  ('IE', 'FraudSMART (BPFI)', 'scam', 'https://www.fraudsmart.ie/', '',
   'Official Irish banking-industry fraud awareness and reporting resource.', '2026-08-01', 'active'),
  ('DE', 'BSI — Bürger-CERT', 'cybercrime', 'https://www.bsi.bund.de/', '',
   'Official German federal office for information security.', '2026-08-01', 'active'),
  ('NL', 'Fraudehelpdesk', 'scam', 'https://www.fraudehelpdesk.nl/', '088-7867372',
   'Official Dutch fraud help desk.', '2026-08-01', 'active'),
  ('AE', 'eCrime.ae', 'cybercrime', 'https://www.ecrime.ae/', '',
   'Official UAE platform for reporting cybercrime.', '2026-08-01', 'active')
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- RAG knowledge chunks (trusted guidance only)
-- ---------------------------------------------------------------------------
insert into public.document_chunks (title, content, source_type, trust_level) values
  ('Your account was hacked — what to do now',
   'If your account is hacked: 1) change the password immediately and log out of all devices, 2) turn on two-factor authentication, 3) check recovery email and phone, 4) tell a trusted adult, 5) report to the platform support and to the official reporting organisation for your country.',
   'knowledge', 'trusted_official'),
  ('You shared a one-time code (OTP)',
   'If you sent a one-time code to someone by mistake: that code is a key to your account. Tell a trusted adult right away, log out of all devices, change your password, and check for new devices on your account. Contact the real company through its official support channel.',
   'knowledge', 'trusted_official'),
  ('Strong passwords and passphrases',
   'Use a passphrase: 3 or 4 random words joined together, at least 12 characters. Use a different password for every account. A password manager can create and remember them for you. Never share passwords, even with friends.',
   'knowledge', 'trusted_internal'),
  ('Two-factor authentication (2FA)',
   '2FA adds a second step after your password, like a code from an app, a security key, or biometrics. Turn it on for email, social media, gaming and bank apps. Prefer authenticator apps over SMS codes when the app supports them.',
   'knowledge', 'trusted_internal'),
  ('Red flags in a phishing message',
   'A message is suspicious if it creates urgency, asks for a password or code, uses a wrong sender address, contains odd links, or asks you to pay with gift cards. When in doubt, type the official website yourself instead of clicking the link.',
   'knowledge', 'trusted_official'),
  ('Safe public Wi-Fi use',
   'Public Wi-Fi can be intercepted. Avoid logging into important accounts on open networks; use your mobile data or a trusted VPN instead. Make sure websites show https and never enter passwords on unfamiliar login pages.',
   'knowledge', 'trusted_internal'),
  ('If money was lost to a scam',
   'If you or your family lost money to a scam: tell a trusted adult immediately, contact the bank or payment provider, keep all evidence (screenshots, receipts), and report to the official reporting organisation for your country. Do not pay any more money to the scammer.',
   'knowledge', 'trusted_official'),
  ('Malware on your device',
   'If you suspect malware: stop using the device for important accounts, run a reputable security scan, remove suspicious apps, change passwords from a different device, and tell a trusted adult.',
   'knowledge', 'trusted_internal'),
  ('Personal information that should stay private',
   'Never share passwords, one-time codes, ID documents, bank cards, home addresses or school details with strangers online. Scammers can combine small pieces of information to steal your identity.',
   'knowledge', 'trusted_official'),
  ('Reporting scams to official organisations',
   'MATRIX AI never invents reporting websites. Reporting guidance always comes from the verified reporting resources database, which contains official organisations such as the FTC, Action Fraud, Scamwatch and the Canadian Anti-Fraud Centre.',
   'knowledge', 'trusted_internal')
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- Courses
-- ---------------------------------------------------------------------------
insert into public.courses (slug, title, description, level, duration_minutes, icon, sort_order) values
  ('cyber-safety-basics', 'Cyber Safety Basics', 'Learn the ground rules of staying safe online — accounts, messages, and everyday habits.', 'beginner', 40, 'shield', 1),
  ('phishing-scam-detection', 'Phishing & Scam Detection', 'Learn to recognise phishing, fake shops and scams before they hurt you.', 'beginner', 45, 'fish', 2),
  ('password-mfa-security', 'Password & MFA Security', 'Create strong passwords, use a password manager and turn on two-factor authentication.', 'beginner', 35, 'key', 3),
  ('social-media-security', 'Social Media Security', 'Control who sees your posts, avoid oversharing, and handle cyberbullying safely.', 'beginner', 40, 'at-sign', 4),
  ('privacy-digital-footprint', 'Privacy & Digital Footprint', 'Understand what your digital footprint is and how to keep your privacy.', 'intermediate', 45, 'eye-off', 5),
  ('device-security', 'Device Security', 'Keep your phone, laptop and accounts safe with updates, locks and backups.', 'beginner', 35, 'smartphone', 6),
  ('cybersecurity-fundamentals', 'Cybersecurity Fundamentals', 'Go deeper: how attacks work, how defenders think, and safe lab learning.', 'intermediate', 60, 'brain', 7)
on conflict (slug) do nothing;

-- Modules: (course slug, title, description, sort)
insert into public.course_modules (course_id, title, description, sort_order)
select c.id, v.title, v.description, v.sort
from (values
  ('cyber-safety-basics', 'Your Online Accounts', 'Why accounts matter and how they get taken over.', 1),
  ('cyber-safety-basics', 'Safe Messaging Habits', 'How to handle messages from people you do not know.', 2),
  ('cyber-safety-basics', 'When Something Goes Wrong', 'The calm, correct steps when something bad happens.', 3),
  ('phishing-scam-detection', 'What Phishing Looks Like', 'Anatomy of a phishing message.', 1),
  ('phishing-scam-detection', 'Common Scam Families', 'Shopping, jobs, prizes, tech support and more.', 2),
  ('phishing-scam-detection', 'How to Check and Report', 'Verifying messages and reporting scams.', 3),
  ('password-mfa-security', 'Passwords That Work', 'Passphrases and password managers.', 1),
  ('password-mfa-security', 'Two-Factor Authentication', 'The second lock on your accounts.', 2),
  ('password-mfa-security', 'Recovery and Backup Codes', 'Keeping access when things go wrong.', 3),
  ('social-media-security', 'Privacy Settings', 'Who can see what you post.', 1),
  ('social-media-security', 'Oversharing and Strangers', 'What not to post and how to handle strangers.', 2),
  ('social-media-security', 'Cyberbullying and Reporting', 'Handling online harassment safely.', 3),
  ('privacy-digital-footprint', 'What Is a Digital Footprint', 'The trail you leave online.', 1),
  ('privacy-digital-footprint', 'Data Brokers and Trackers', 'Who collects your data and why.', 2),
  ('privacy-digital-footprint', 'Privacy on Every Device', 'Browser, phone and app privacy habits.', 3),
  ('device-security', 'Keeping Devices Updated', 'Updates, locks and screen time hygiene.', 1),
  ('device-security', 'Safe Downloads and Apps', 'Where apps come from and what permissions mean.', 2),
  ('device-security', 'Backups and Wipes', 'Protecting your data and starting fresh safely.', 3),
  ('cybersecurity-fundamentals', 'How Attacks Work', 'Malware, social engineering and exploits explained.', 1),
  ('cybersecurity-fundamentals', 'The Defender Mindset', 'Layered defence and the human firewall.', 2),
  ('cybersecurity-fundamentals', 'Ethical Hacking and Safe Labs', 'How to learn hacking skills safely and legally.', 3)
) as v(course_slug, title, description, sort)
join public.courses c on c.slug = v.course_slug
on conflict (course_id, sort_order) do nothing;

-- Lessons: (course, module, title, body, sort)
insert into public.lessons (module_id, title, body, sort_order)
select m.id, v.title, v.body, v.sort
from (values
  -- Cyber Safety Basics
  ('cyber-safety-basics','Your Online Accounts','Your email is the master key to everything you do online.',
   'Your email address is usually the "master key": if someone takes over your email, they can reset passwords for your other accounts. That is why your email password should be the strongest one you have, and why you should never share it — even with your closest friends. Turn on two-factor authentication for email first, before any other account. If an account is important, it deserves a unique password. Use your school or personal email carefully: never use it to sign up for random websites, because those sites can be hacked or sold.', 1),
  ('cyber-safety-basics','How Accounts Get Taken Over','Most account takeovers are not genius hacks — they are leaked passwords and shared codes.',
   'Most account takeovers happen because of leaked passwords (a website you used got hacked), reused passwords (same password everywhere), or shared one-time codes. A scammer does not need to "hack" you if you hand them the key. Watch for signs an account is compromised: messages sent that you did not write, password reset emails you did not request, or a "logged in from a new device" alert you did not cause. If you see these signs, act calmly: change the password, log out of all devices, and tell a trusted adult.', 2),
  ('cyber-safety-basics','Messages from People You Do Not Know','Strangers online can pretend to be anyone — including your friends.',
   'Scammers fake messages from friends, companies and even police. A friend asking for a code or money in a strange way? Call them or ask in person. A company asking for your password? Real companies never do that. Before replying to an unexpected message, ask: did I expect this? Does it push me to act fast? Does it ask for a secret? If yes to any of these, do not reply — and never click links in messages you did not expect.', 1),
  ('cyber-safety-basics','The Pause Rule','Slowing down defeats most scams, because scams run on speed.',
   'Scams work by rushing you: "act now", "your account will close", "you won but must pay today". The Pause Rule is simple: when a message makes you feel rushed, stop. Do not click, do not reply, do not send money or codes. Take ten minutes. Check with a trusted adult. Type the official website yourself instead of clicking the link. Almost every scam collapses when you slow down.', 2),
  ('cyber-safety-basics','If Something Goes Wrong','Bad things happen — the right response fixes most of the damage.',
   'If you clicked a suspicious link, shared a code, or lost money: you are not in trouble, and the fastest way to limit damage is to act quickly and calmly. Tell a trusted adult immediately. Change the affected passwords from a different device. Log out of all sessions. Keep screenshots as evidence. Use the Emergency help ("I Need Help Now") section for step-by-step guidance specific to what happened. The worst thing you can do is hide it or wait.', 1),
  ('cyber-safety-basics','Getting Help Without Judgment','MATRIX AI is a judgment-free space — and so should your reporting experience be.',
   'Everyone makes mistakes online; that is how we learn. The platform never blames you, and neither should you blame yourself. You can ask the AI anything about cybersecurity, use Emergency mode for step-by-step help, or report a scam to the official reporting organisation. If you are being pressured, threatened or blackmailed online, that is never your fault — tell a trusted adult or a support service right away.', 2),
  -- Phishing & Scam Detection
  ('phishing-scam-detection','Anatomy of a Phishing Message','Every phishing message has a small set of ingredients.',
   'Phishing messages usually contain: an urgent demand, a fake sender address (like amaz0n-support@mail.ru), a link to a lookalike login page, and a request for a secret (password, code, card number). The message may be an email, SMS, WhatsApp, or a chat in a game. Look at the language: real companies do not send "Dear customer, your account will be deleted in 24 hours" emails. When a message asks for a secret, it is a scam, full stop.', 1),
  ('phishing-scam-detection','Spotting Lookalike Links','Scammers hide fake addresses behind friendly text.',
   'The text of a link can say anything — "click here" — while the real address goes somewhere else. Hover over (or long-press) a link to preview the true address before clicking. Look for misspellings of real brands (paypa1, faceb00k) and unusual endings (.xyz, .top, .shop). In messages from friends, the address is still the thing to check. When in doubt, do not click: open a new tab and type the official site yourself.', 2),
  ('phishing-scam-detection','Fake Shops and Fake Goods','Too-good-to-be-true prices are the main ingredient of shopping scams.',
   'Fake shops copy real store designs, use stolen logos, and offer huge discounts. They usually only accept bank transfers or gift cards, which leave no protection. Before buying: check the domain age and spelling, search "<shop name> + scam", look for a real phone number and physical address, and pay with buyer-protected methods. If a deal looks impossible, it is a scam — walk away.', 1),
  ('phishing-scam-detection','Job, Prize and Tech-Support Traps','Three scam families that target teens specifically.',
   'Job scams offer easy money for "tasks" then demand fees or ID photos. Prize scams say you won something you never entered and ask for a "fee" to release it. Tech-support scams pop up with virus warnings and ask you to call a number or pay to "fix" your device. Real jobs do not charge you, real prizes do not ask for money, and real tech companies never call you about viruses. If it costs money to receive money, it is a scam.', 2),
  ('phishing-scam-detection','Verifying a Suspicious Message','A simple checklist turns suspicion into certainty.',
   'When a message feels off, run the checklist: 1) Who really sent it? (check the raw address, not the display name). 2) Did I expect this? 3) Does it create urgency? 4) Does it ask for a secret or money? 5) Is the link address correct? If two or more checkboxes are ticked, treat it as a scam: do not reply, do not click, report it. You can also paste the message into the MATRIX AI chat for a safe analysis.', 1),
  ('phishing-scam-detection','Reporting a Scam','Reporting protects you and everyone else.',
   'Reporting a scam takes two minutes and helps platforms and authorities take it down. Save evidence first: screenshots of the message, the sender address, and the link (without clicking it). Then report through the platform (most apps have a report button), and report to the official reporting organisation for your country using the verified reporting resources in this app. MATRIX AI never invents reporting websites — it always uses verified official contacts.', 2),
  -- Password & MFA
  ('password-mfa-security','Passphrases Beat Passwords','Length beats complexity when it comes to passwords.',
   'A passphrase is 3–4 random words put together, like "purple-lantern-cloud-42". It is long, easy for you to remember, and hard for computers to guess. Avoid personal details (your name, birthday, pet) because scammers can find those online. Never reuse passwords: when one site leaks your password, scammers try it on every other site. That is how most accounts get taken over.', 1),
  ('password-mfa-security','Password Managers','Let software create and remember unique passwords for you.',
   'A password manager is an app that generates strong random passwords and stores them in one encrypted vault protected by one master passphrase. You only need to remember the master passphrase. Use one on your phone and computer, turn on its auto-lock, and never share the vault. If you are under 18, ask a trusted adult to help you set it up — it is one of the highest-impact security upgrades available.', 2),
  ('password-mfa-security','What 2FA Is and Why It Matters','A second lock stops stolen passwords from being enough.',
   'Two-factor authentication (2FA) means that logging in needs your password plus a second proof: a code from an authenticator app, a hardware security key, or your fingerprint/face. If a scammer steals your password but not your phone, they still cannot get in. Turn on 2FA for email, social media, gaming and bank apps. Prefer authenticator apps (like Google Authenticator or Authy) over SMS codes when possible.', 1),
  ('password-mfa-security','Setting Up 2FA the Right Way','The setup moment is when most 2FA mistakes happen.',
   'When you enable 2FA, save the recovery codes somewhere safe — a printed note or a password manager — because if you lose your phone, those codes are your only way back in. Never screenshot recovery codes into your photo gallery where other apps can read them. After setup, test it: log out and log back in. If a message asks for your 2FA code, remember: the code is only for the login screen you opened yourself — anyone who asks for it by message is a scammer.', 2),
  ('password-mfa-security','Recovery Options','Recovery email and phone are the emergency exits of your account.',
   'Every important account lets you add recovery options: a backup email or a phone number. Keep them up to date — an old recovery email is how accounts get lost forever. Beware of "account recovery" scams that claim to be support and ask for codes or money to restore an account. Real recovery is free and never asks for your password. If you lose access, use the official recovery flow on the real website only.', 1),
  ('password-mfa-security','Auditing Your Passwords','A yearly password check-up is a healthy habit.',
   'Once a year (or after any scare), do a password audit: list your important accounts, check that each has a unique strong password and 2FA, remove old unused accounts (they can be hacked and forgotten), and update recovery email/phone. Security check-up tools from password managers can show you which passwords were leaked in data breaches — change those first.', 2),
  -- Social Media Security
  ('social-media-security','Reading Privacy Settings','Privacy settings are a choose-your-own-adventure — pick the right one.',
   'On every social platform, go through settings and decide: who can see your posts (friends only beats public), who can message you, who can find you by phone/email, and whether your profile appears in search engines. Check the settings on each app you use — they are all different. Review them again after app updates, because defaults can change. A private profile is not paranoid; it is normal.', 1),
  ('social-media-security','What to Never Post','Some things should never go online, even to friends.',
   'Never post: your exact home address, school address, ID documents or tickets (QR codes can be scanned), bank card photos, passwords or codes, or photos that show your location in real time. Even "private" posts can be screenshotted by someone you trusted. Think of everything you post as potentially public forever. A good rule: if you would not show it on a big screen at school, do not post it.', 2),
  ('social-media-security','Handling Stranger Requests','Strangers use kindness, compliments and gifts to earn trust.',
   'Not every stranger online is a scammer — but the ones who are use the same playbook: flattery, secrets ("this is our private thing"), gifts, and slowly asking for personal details, photos or money. If someone you have never met in person asks for money, gift cards, private photos, or to keep your chats secret — that is a massive red flag. Tell a trusted adult. You never owe a stranger anything, online or offline.', 1),
  ('social-media-security','Location and Live Features','Sharing where you are, live, is sharing your schedule.',
   'Location tags on posts tell people where you are now; live features tell people where you are right now. Turn off precise location for social apps, post places after you have left them, and avoid live-streaming from home. Photos taken with a phone carry hidden location data — platforms may strip it, but not always. Check each app\'s location settings and set them to "never" or "while using".', 2),
  ('social-media-security','What Cyberbullying Looks Like','Bullying online is still bullying — and it is not your fault.',
   'Cyberbullying includes repeated mean messages, spreading rumours, fake accounts impersonating you, sharing your private photos, and excluding or threatening you. It often happens where adults cannot see it. If it is happening to you: do not respond to the bully (that feeds the fire), save evidence (screenshots with dates), block the accounts, and tell a trusted adult or a school counsellor. Most platforms have anti-bullying reporting tools; use them.', 1),
  ('social-media-security','Blocking, Muting and Reporting','The block button is a health tool, not a punishment.',
   'You are allowed to block anyone, any time, for any reason — you do not owe anyone access to you. Learn the platform\'s flow: block the account, report harassment with evidence, and tell a trusted adult if it escalates. If a bully switches accounts, keep reporting and keep evidence. In many countries, severe cyberbullying and threats are illegal — reporting to the official reporting organisation is an option, especially if you feel unsafe.', 2),
  -- Privacy & Digital Footprint
  ('privacy-digital-footprint','Your Digital Footprint','Everything you do online leaves a trail that lasts.',
   'Your digital footprint is the trail of everything you post, search, like, buy and share — plus what others post about you. It is built from social posts, gaming profiles, school projects, comments, and even old accounts you forgot. Once something is online, it can be copied, archived and screenshotted. Before posting, ask: would I be okay seeing this on a screen in ten years? Because it might be there.', 1),
  ('privacy-digital-footprint','The Footprint Audit','Find out what the internet knows about you.',
   'A footprint audit: 1) search your name in a search engine and note what comes up, 2) list every account you ever made, 3) delete the ones you do not use, 4) tighten privacy settings on the rest, 5) remove old posts that reveal too much. Do this with a trusted adult the first time. Deleting old accounts is one of the best privacy moves a teenager can make.', 2),
  ('privacy-digital-footprint','Who Collects Your Data','Free apps are not free — data is the payment.',
   'Many free apps and websites make money from your data: your interests, location, friends and habits are collected, combined and sold to advertisers and data brokers. This is why you see eerily relevant ads. Check app permissions, use "ask every time" for location, reject unnecessary tracking cookies, and use privacy-friendly browsers. Reading what data an app collects is a real skill — start with the app store\'s data-safety labels.', 1),
  ('privacy-digital-footprint','Trackers and Cookies','Cookies can be harmless or creepy — know the difference.',
   'Cookies are small files websites use to remember you. Some are needed to stay logged in; others track you across sites to build an advertising profile. Most browsers let you block third-party cookies and clear history. Use private/incognito windows for sensitive research, and consider privacy-focused search engines. When a site asks for cookie consent, "reject non-essential" is a perfectly good choice.', 2),
  ('privacy-digital-footprint','Privacy on Your Phone','Your phone knows where you are, what you say, and who you talk to.',
   'Phone privacy starts with the lock screen (PIN or biometric), then app permissions: review which apps have camera, microphone, contacts, and location access, and revoke the ones that do not need it. Turn off personalised ads where the OS lets you, check app-by-app location settings, and be careful installing "flashlight" apps that want your contacts — they have no reason to need them.', 1),
  ('privacy-digital-footprint','Sharing with Care','Oversharing is a habit; sharing with care is a skill.',
   'Before sharing personal information, ask: who needs this, why do they need it, and what could go wrong if it leaked? Legitimate sites rarely need your full name, birthdate, address and phone at once. Use nicknames where real names are not required, avoid birthdate fields where possible, and be wary of quizzes and "personality tests" that harvest data — they are often data-collection traps. Sharing less is always an option, and it is always okay.', 2),
  -- Device Security
  ('device-security','Updates Are Security','That annoying update popup is actually a security patch.',
   'Updates fix security holes that attackers know about — the moment a fix is released, attackers race to break the unfixed versions. Turn on automatic updates for your phone, laptop, apps and browser. Restart devices regularly so updates can finish. If a device is too old to update anymore, stop using it for important accounts like banking and email; old devices are the easiest targets.', 1),
  ('device-security','Locks and Screen Hygiene','The physical lock is the first line of defence.',
   'A phone or laptop without a lock is an open door: anyone who picks it up has your accounts, photos and messages. Set a strong PIN or biometric lock, enable auto-lock after a short time, and never share your unlock code — even with friends (they might lose the device, or the code can be screenshotted). Lock your screen when you walk away, even at home. Log out of shared computers when you are done.', 2),
  ('device-security','Where Apps Come From','Official app stores are the safe door; everywhere else is a gamble.',
   'Install apps only from official stores (Google Play, App Store, Microsoft Store) and check the developer name, download counts and reviews. "Sideloading" apps from random websites or links in messages is how most mobile malware spreads. Before installing, read the permission list: a game does not need your contacts, a wallpaper app does not need your camera. When an app asks for a strange permission, that is the moment to say no.', 1),
  ('device-security','Spotting Fake Apps','Fake apps borrow real names and icons to trick you.',
   'Fake apps appear in search results and ads with slightly wrong names (WhatsApp+), copied icons, and a handful of downloads. Clues: very few downloads, recent creation date, broken grammar, or demands for payment before use. Check the developer name against the official one. If an app asks for accessibility permissions or device-admin rights, that is a serious red flag — those powers can read your screen.', 2),
  ('device-security','Backups','A backup is your safety net against loss, breakage and ransomware.',
   'Backups mean your photos and files are not lost if a device breaks, is stolen, or is locked by malware. Enable automatic backup to a cloud account you control (with 2FA on that account!), or back up to an external drive. Test a restore once in a while. For important school work, keep copies in two places. A backup you have never tested is a hope, not a plan.', 1),
  ('device-security','Selling, Recycling and Wiping','Wipe before you let a device go.',
   'Before selling, trading or recycling a device: back up what you need, then do a factory reset (and for computers, a full disk wipe if possible). Log out of every account first, and remove SIM/memory cards. A factory reset is not optional — the next owner should never see your photos, messages or saved passwords. Also remove your account from the device so it cannot be remotely accessed later.', 2),
  -- Cybersecurity Fundamentals
  ('cybersecurity-fundamentals','Social Engineering','The easiest way past any security is a human.',
   'Social engineering is manipulating people into giving away access — the "hacker" is usually a conversation, not code. Phishing, fake phone calls, impersonation and urgent requests are all social engineering. Defenders train themselves to notice when a request asks for something unusual, creates pressure, or plays on fear, greed or helpfulness. The human firewall — knowing when to say no — is the most important control in any system, including your own accounts.', 1),
  ('cybersecurity-fundamentals','Malware Families','Malware is not one thing — it is a family of threats.',
   'Common malware families: viruses (attach to files), worms (spread by themselves), Trojans (hide inside useful-looking software), ransomware (locks your files and demands payment), spyware (watches you silently), and adware (floods ads). Key idea: most malware needs a human to let it in — a fake download, a malicious link, or a USB stick. Updates, safe downloads and suspicious-link habits block most of the family at the door.', 2),
  ('cybersecurity-fundamentals','Exploits and Vulnerabilities','A vulnerability is a bug with a price tag.',
   'A vulnerability is a flaw in software that attackers can abuse; an exploit is the attack that uses it. That is why updates matter: patches close known vulnerabilities. In cybersecurity, people who find vulnerabilities can report them responsibly (responsible disclosure) instead of exploiting them — companies often reward this through bug bounty programs. Learning how vulnerabilities are found and fixed is a core defender skill.', 1),
  ('cybersecurity-fundamentals','Defence in Depth','Layered defence means no single failure is fatal.',
   'Defence in depth means several independent layers: strong unique passwords, 2FA, updated software, cautious clicking, backups, and limited sharing. If one layer fails (say, a password leaks), the next one (2FA) still holds. Security is not one perfect action; it is many imperfect ones stacked. The same idea applies to your accounts: recovery options, alerts and regular check-ups are layers too.', 2),
  ('cybersecurity-fundamentals','What Ethical Hacking Is','Hacking skills are like fire — useful or destructive depending on how you use them.',
   'Ethical hacking (white hat) is using hacking skills to find and fix weaknesses with permission. Bug bounty platforms let researchers test companies\' systems legally and get paid for findings. The line is permission: testing a system you do not own, or without authorisation, is illegal and harmful. Never "test" your school, someone else\'s account, or any system without written permission. The skills that make a great defender are the same skills that make a dangerous attacker — choose the defender path.', 1),
  ('cybersecurity-fundamentals','Your Path in Cybersecurity','From learner to white hat: a realistic roadmap.',
   'If you love this stuff, the path is: build strong fundamentals (networking, Linux, programming), learn on legal sandboxes (TryHackMe, HackTheBox, picoCTF), earn beginner certifications when old enough, join CTF (capture the flag) competitions, and eventually pursue responsible disclosure or bug bounty programs. School subjects that help: maths, computer science, and English (for writing clear security reports). Never break the law to "prove" skills — the white hat community will not respect it, and the law will not ignore it.', 2)
) as v(course_slug, module_title, title, body, sort)
join public.course_modules m on m.title = v.module_title
join public.courses c on c.id = m.course_id and c.slug = v.course_slug
on conflict (module_id, sort_order) do nothing;

-- Quizzes: one per module
insert into public.quizzes (module_id, title, pass_percent, sort_order)
select m.id, 'Quiz: ' || m.title, 60, 1
from public.course_modules m
on conflict (module_id, sort_order) do nothing;

-- Questions (unique text — matched by quiz + text below)
insert into public.quiz_questions (quiz_id, question, explanation, sort_order)
select q.id, v.question, v.explanation, v.sort
from (values
  ('Your Online Accounts', 'Which account should have your strongest password and 2FA first?',
   'Email is the master key — it can reset your other passwords.', 1),
  ('Your Online Accounts', 'How do most accounts actually get taken over?',
   'Leaked, reused or shared passwords — not mysterious "hacks".', 2),
  ('Your Online Accounts', 'A friend sends a strange link asking for your code. What do you do first?',
   'Verify with your friend in person or by a call before doing anything.', 3),
  ('Safe Messaging Habits', 'Which of these is a strong sign of a scam message?',
   'Urgency ("act now!") plus a request for a secret is the classic scam recipe.', 1),
  ('Safe Messaging Habits', 'The Pause Rule means…',
   'When a message rushes you, stop before clicking, replying or paying.', 2),
  ('Safe Messaging Habits', 'Real companies usually ask for your password by message.',
   'False — real companies never ask for passwords or codes in messages.', 3),
  ('When Something Goes Wrong', 'You clicked a suspicious link. The best first step is…',
   'Act quickly and calmly, tell a trusted adult, change passwords from another device.', 1),
  ('When Something Goes Wrong', 'If you made a mistake online, MATRIX AI will…',
   'Help you without judgment — everyone makes mistakes, that is how we learn.', 2),
  ('When Something Goes Wrong', 'Which is the right attitude after a security mistake?',
   'Mistakes are learning moments; hiding them makes things worse.', 3),
  ('What Phishing Looks Like', 'Which is a red flag in an email?',
   'A request for your password or one-time code is always a red flag.', 1),
  ('What Phishing Looks Like', 'The link text says "secure-login.com" but the real address is "secure-log1n.xyz". You should…',
   'Never click; open the official site by typing it yourself.', 2),
  ('What Phishing Looks Like', 'Phishing can arrive by…',
   'All of these — email, SMS, WhatsApp, games and social chats.', 3),
  ('Common Scam Families', 'A "job" pays you to like videos, then asks for a fee to unlock more tasks. This is…',
   'A classic task scam — real jobs never charge you money.', 1),
  ('Common Scam Families', 'A prize message says you won a contest you never entered and must pay a fee. You should…',
   'Ignore it — real prizes never ask winners to pay.', 2),
  ('Common Scam Families', 'A pop-up says your device is infected and shows a phone number to call. This is…',
   'A tech-support scam — real companies never call you about viruses.', 3),
  ('How to Check and Report', 'Before reporting a scam you should…',
   'Save evidence first: screenshots of the message, sender and link.', 1),
  ('How to Check and Report', 'Where does MATRIX AI get reporting contacts from?',
   'From the verified reporting resources database — it never invents websites.', 2),
  ('How to Check and Report', 'Reporting a scam helps…',
   'You and everyone else — reports help platforms take scams down.', 3),
  ('Passwords That Work', 'What is the best kind of password?',
   'A long passphrase of random words, unique per account.', 1),
  ('Passwords That Work', 'Why should you never reuse passwords?',
   'When one site leaks it, scammers try it on all your other accounts.', 2),
  ('Passwords That Work', 'A password manager helps you by…',
   'Creating and remembering a unique strong password for every account.', 3),
  ('Two-Factor Authentication', '2FA means…',
   'Password plus a second proof, like a code from an authenticator app.', 1),
  ('Two-Factor Authentication', 'Someone messages you asking for your 2FA code. You should…',
   'Never share it — codes are only for login screens you opened yourself.', 2),
  ('Two-Factor Authentication', 'Which 2FA method is usually preferred over SMS codes?',
   'Authenticator apps are generally safer than SMS codes.', 3),
  ('Recovery and Backup Codes', 'Where should you keep recovery codes?',
   'In a safe place like a printed note or your password manager — never in screenshots.', 1),
  ('Recovery and Backup Codes', 'Your recovery email is out of date. This matters because…',
   'An outdated recovery email can lock you out of your own account.', 2),
  ('Recovery and Backup Codes', '"Account recovery support" asks you to pay to restore your account. This is…',
   'A scam — real account recovery is free.', 3),
  ('Privacy Settings', 'A private profile means…',
   'Only approved people can see your posts and info.', 1),
  ('Privacy Settings', 'After an app update you should…',
   'Re-check privacy settings — updates can change defaults.', 2),
  ('Privacy Settings', 'Who can see your posts if you share them "only to friends"?',
   'Your friends — but they can screenshot and share further, so still post with care.', 3),
  ('Oversharing and Strangers', 'Which should you never post online?',
   'All of these: your address, ID documents, and tickets with QR codes.', 1),
  ('Oversharing and Strangers', 'A stranger online asks you to keep your chats a secret from your parents. This is…',
   'A serious red flag — tell a trusted adult.', 2),
  ('Oversharing and Strangers', 'You owe a stranger online…',
   'Nothing — you never owe anyone access to you.', 3),
  ('Cyberbullying and Reporting', 'The first step when cyberbullied is…',
   'Do not respond; save evidence and block the account.', 1),
  ('Cyberbullying and Reporting', 'Blocking someone who harasses you is…',
   'Always allowed — it is a health tool, not a punishment.', 2),
  ('Cyberbullying and Reporting', 'Severe threats online should be…',
   'Reported to the platform, a trusted adult, and possibly authorities.', 3),
  ('What Is a Digital Footprint', 'Your digital footprint is…',
   'The lasting trail of everything you and others post and do online.', 1),
  ('What Is a Digital Footprint', 'An old account you forgot about can…',
   'Still exist and reveal your data — delete unused accounts.', 2),
  ('What Is a Digital Footprint', 'Once something is online, it can…',
   'Be copied, archived and screenshotted — treat it as permanent.', 3),
  ('Data Brokers and Trackers', 'Free apps often make money by…',
   'Collecting and selling your data to advertisers and data brokers.', 1),
  ('Data Brokers and Trackers', 'A "personality test" that asks lots of personal questions is…',
   'Often a data-collection trap — be careful what you fill in.', 2),
  ('Data Brokers and Trackers', 'Third-party cookies are used mainly to…',
   'Track you across websites for advertising profiles.', 3),
  ('Privacy on Every Device', 'An app wants your contacts but has no reason to. You should…',
   'Deny the permission — apps should only get what they need.', 1),
  ('Privacy on Every Device', 'The best location setting for most apps is…',
   '"While using" or "ask every time" — not "always".', 2),
  ('Privacy on Every Device', 'Your phone lock screen is important because…',
   'Whoever picks up your phone gets your accounts and messages.', 3),
  ('Keeping Devices Updated', 'Software updates mostly exist to…',
   'Fix security holes that attackers exploit.', 1),
  ('Keeping Devices Updated', 'A device that no longer receives updates should…',
   'Not be used for important accounts like email or banking.', 2),
  ('Keeping Devices Updated', 'Automatic updates are…',
   'A good idea — they patch devices without you remembering to.', 3),
  ('Safe Downloads and Apps', 'The safest place to install apps is…',
   'The official app store, checking the developer name.', 1),
  ('Safe Downloads and Apps', 'An app asking for device-admin or accessibility rights is…',
   'A serious red flag — those powers can read your screen.', 2),
  ('Safe Downloads and Apps', 'A game asking for your contacts permission is…',
   'Suspicious — games do not need your contacts.', 3),
  ('Backups and Wipes', 'A backup protects you from…',
   'Device loss, breakage and ransomware.', 1),
  ('Backups and Wipes', 'Before selling a phone you should…',
   'Back up, log out of accounts, remove SIM/cards, and factory reset.', 2),
  ('Backups and Wipes', 'A backup you have never tested is…',
   'A hope, not a plan — test a restore sometimes.', 3),
  ('How Attacks Work', 'Social engineering works by…',
   'Manipulating people instead of breaking technology.', 1),
  ('How Attacks Work', 'Ransomware is malware that…',
   'Locks your files and demands payment to unlock them.', 2),
  ('How Attacks Work', 'Most malware gets in because…',
   'A human lets it in — via fake downloads, links or USB sticks.', 3),
  ('The Defender Mindset', 'Defence in depth means…',
   'Layered defences so one failure is not fatal.', 1),
  ('The Defender Mindset', 'The "human firewall" is…',
   'People who recognise and stop social engineering.', 2),
  ('The Defender Mindset', 'Which layer protects you if a password leaks?',
   '2FA — the second factor still stops the attacker.', 3),
  ('Ethical Hacking and Safe Labs', 'The line between ethical and illegal hacking is…',
   'Permission — testing systems you do not own is illegal.', 1),
  ('Ethical Hacking and Safe Labs', 'Good places to practise hacking legally are…',
   'Sandboxes like TryHackMe, HackTheBox and picoCTF.', 2),
  ('Ethical Hacking and Safe Labs', 'Bug bounty programs work by…',
   'Companies paying researchers to find and report vulnerabilities.', 3)
) as v(module_title, question, explanation, sort)
join public.quizzes q on q.title = 'Quiz: ' || v.module_title
join public.course_modules m on m.id = q.module_id and m.title = v.module_title
on conflict do nothing;

-- Options (matched by exact question text — all question texts are unique)
insert into public.quiz_options (question_id, option_text, is_correct, sort_order)
select qq.id, v.option_text, v.is_correct, v.sort
from (values
  ('Which account should have your strongest password and 2FA first?', 'Email', true, 1),
  ('Which account should have your strongest password and 2FA first?', 'Gaming account', false, 2),
  ('Which account should have your strongest password and 2FA first?', 'A social media account you rarely use', false, 3),
  ('How do most accounts actually get taken over?', 'Mysterious super-hackers', false, 1),
  ('How do most accounts actually get taken over?', 'Leaked, reused or shared passwords', true, 2),
  ('How do most accounts actually get taken over?', 'Aliens', false, 3),
  ('A friend sends a strange link asking for your code. What do you do first?', 'Send the code — it is a friend', false, 1),
  ('A friend sends a strange link asking for your code. What do you do first?', 'Verify with them in person or by a call', true, 2),
  ('A friend sends a strange link asking for your code. What do you do first?', 'Click the link to check it', false, 3),
  ('Which of these is a strong sign of a scam message?', 'It uses emojis', false, 1),
  ('Which of these is a strong sign of a scam message?', 'Urgency plus a request for a secret', true, 2),
  ('Which of these is a strong sign of a scam message?', 'It is written in your language', false, 3),
  ('The Pause Rule means…', 'Stop and think before clicking, replying or paying', true, 1),
  ('The Pause Rule means…', 'Pause your video games while messaging', false, 2),
  ('The Pause Rule means…', 'Wait a week before using the internet', false, 3),
  ('Real companies usually ask for your password by message.', 'True', false, 1),
  ('Real companies usually ask for your password by message.', 'False — they never ask for passwords or codes in messages', true, 2),
  ('You clicked a suspicious link. The best first step is…', 'Ignore it and hope for the best', false, 1),
  ('You clicked a suspicious link. The best first step is…', 'Tell a trusted adult and change passwords from another device', true, 2),
  ('You clicked a suspicious link. The best first step is…', 'Send the link to friends to test it', false, 3),
  ('If you made a mistake online, MATRIX AI will…', 'Shame you', false, 1),
  ('If you made a mistake online, MATRIX AI will…', 'Help you without judgment', true, 2),
  ('If you made a mistake online, MATRIX AI will…', 'Ban your account', false, 3),
  ('Which is the right attitude after a security mistake?', 'Hide it — mistakes are embarrassing', false, 1),
  ('Which is the right attitude after a security mistake?', 'Mistakes are learning moments; tell a trusted adult', true, 2),
  ('Which is the right attitude after a security mistake?', 'Blame whoever sent the message', false, 3),
  ('Which is a red flag in an email?', 'A request for your password or one-time code', true, 1),
  ('Which is a red flag in an email?', 'The sender used your first name', false, 2),
  ('Which is a red flag in an email?', 'It was sent on a weekday', false, 3),
  ('The link text says "secure-login.com" but the real address is "secure-log1n.xyz". You should…', 'Click it — the text says secure', false, 1),
  ('The link text says "secure-login.com" but the real address is "secure-log1n.xyz". You should…', 'Never click; type the official site yourself', true, 2),
  ('The link text says "secure-login.com" but the real address is "secure-log1n.xyz". You should…', 'Forward it to friends to check', false, 3),
  ('Phishing can arrive by…', 'Email only', false, 1),
  ('Phishing can arrive by…', 'SMS and WhatsApp only', false, 2),
  ('Phishing can arrive by…', 'Email, SMS, WhatsApp, games and social chats', true, 3),
  ('A "job" pays you to like videos, then asks for a fee to unlock more tasks. This is…', 'A normal way to earn online', false, 1),
  ('A "job" pays you to like videos, then asks for a fee to unlock more tasks. This is…', 'A classic task scam', true, 2),
  ('A "job" pays you to like videos, then asks for a fee to unlock more tasks. This is…', 'A prize, not a job', false, 3),
  ('A prize message says you won a contest you never entered and must pay a fee. You should…', 'Pay the fee to get your prize', false, 1),
  ('A prize message says you won a contest you never entered and must pay a fee. You should…', 'Ignore it — real prizes never ask winners to pay', true, 2),
  ('A prize message says you won a contest you never entered and must pay a fee. You should…', 'Reply to ask for more details', false, 3),
  ('A pop-up says your device is infected and shows a phone number to call. This is…', 'A tech-support scam', true, 1),
  ('A pop-up says your device is infected and shows a phone number to call. This is…', 'A real virus warning from Microsoft', false, 2),
  ('A pop-up says your device is infected and shows a phone number to call. This is…', 'A prize notification', false, 3),
  ('Before reporting a scam you should…', 'Delete all evidence to stay safe', false, 1),
  ('Before reporting a scam you should…', 'Save evidence: screenshots of the message, sender and link', true, 2),
  ('Before reporting a scam you should…', 'Pay the scammer to stop', false, 3),
  ('Where does MATRIX AI get reporting contacts from?', 'It invents them when needed', false, 1),
  ('Where does MATRIX AI get reporting contacts from?', 'The verified reporting resources database', true, 2),
  ('Where does MATRIX AI get reporting contacts from?', 'Random websites', false, 3),
  ('Reporting a scam helps…', 'Only the reporter', false, 1),
  ('Reporting a scam helps…', 'Everyone — reports help platforms take scams down', true, 2),
  ('What is the best kind of password?', 'Your birthday and name', false, 1),
  ('What is the best kind of password?', 'A long passphrase of random words, unique per account', true, 2),
  ('What is the best kind of password?', 'A short one you can remember easily', false, 3),
  ('Why should you never reuse passwords?', 'It is hard to remember them', false, 1),
  ('Why should you never reuse passwords?', 'A leak on one site lets scammers try it everywhere', true, 2),
  ('Why should you never reuse passwords?', 'Websites compare passwords', false, 3),
  ('A password manager helps you by…', 'Sending your passwords to friends', false, 1),
  ('A password manager helps you by…', 'Creating and remembering a unique password for every account', true, 2),
  ('A password manager helps you by…', 'Making your passwords shorter', false, 3),
  ('2FA means…', 'Two friends authenticate you', false, 1),
  ('2FA means…', 'Password plus a second proof like an app code', true, 2),
  ('2FA means…', 'Two passwords for one account', false, 3),
  ('Someone messages you asking for your 2FA code. You should…', 'Send it — they sound official', false, 1),
  ('Someone messages you asking for your 2FA code. You should…', 'Never share it — codes are only for login screens you opened', true, 2),
  ('Someone messages you asking for your 2FA code. You should…', 'Send it but ask for a code back', false, 3),
  ('Which 2FA method is usually preferred over SMS codes?', 'Authenticator apps', true, 1),
  ('Which 2FA method is usually preferred over SMS codes?', 'Codes written in notes', false, 2),
  ('Which 2FA method is usually preferred over SMS codes?', 'No 2FA at all', false, 3),
  ('Where should you keep recovery codes?', 'In a screenshot in your gallery', false, 1),
  ('Where should you keep recovery codes?', 'In a safe place like a printed note or password manager', true, 2),
  ('Where should you keep recovery codes?', 'In a chat with yourself', false, 3),
  ('Your recovery email is out of date. This matters because…', 'It is used for marketing', false, 1),
  ('Your recovery email is out of date. This matters because…', 'It can lock you out of your own account', true, 2),
  ('Your recovery email is out of date. This matters because…', 'It does not matter at all', false, 3),
  ('"Account recovery support" asks you to pay to restore your account. This is…', 'Normal practice', false, 1),
  ('"Account recovery support" asks you to pay to restore your account. This is…', 'A scam — real recovery is free', true, 2),
  ('A private profile means…', 'Only approved people see your posts', true, 1),
  ('A private profile means…', 'Nobody on the internet can see anything ever', false, 2),
  ('A private profile means…', 'Your posts are hidden from yourself', false, 3),
  ('After an app update you should…', 'Re-check privacy settings — defaults can change', true, 1),
  ('After an app update you should…', 'Delete the app', false, 2),
  ('After an app update you should…', 'Post about the update', false, 3),
  ('Who can see your posts if you share them "only to friends"?', 'Your friends — but they can screenshot and share further', true, 1),
  ('Who can see your posts if you share them "only to friends"?', 'Only you', false, 2),
  ('Who can see your posts if you share them "only to friends"?', 'Nobody', false, 3),
  ('Which should you never post online?', 'Your address, ID documents, and tickets with QR codes', true, 1),
  ('Which should you never post online?', 'Photos of your food', false, 2),
  ('Which should you never post online?', 'Pictures of your homework', false, 3),
  ('A stranger online asks you to keep your chats a secret from your parents. This is…', 'Normal online friendship', false, 1),
  ('A stranger online asks you to keep your chats a secret from your parents. This is…', 'A serious red flag — tell a trusted adult', true, 2),
  ('A stranger online asks you to keep your chats a secret from your parents. This is…', 'A game challenge', false, 3),
  ('You owe a stranger online…', 'A reply within five minutes', false, 1),
  ('You owe a stranger online…', 'Nothing — you never owe anyone access to you', true, 2),
  ('The first step when cyberbullied is…', 'Reply with something harsher', false, 1),
  ('The first step when cyberbullied is…', 'Do not respond; save evidence and block the account', true, 2),
  ('The first step when cyberbullied is…', 'Delete your whole account', false, 3),
  ('Blocking someone who harasses you is…', 'Rude', false, 1),
  ('Blocking someone who harasses you is…', 'Always allowed — it is a health tool', true, 2),
  ('Blocking someone who harasses you is…', 'Only for adults', false, 3),
  ('Severe threats online should be…', 'Ignored', false, 1),
  ('Severe threats online should be…', 'Reported to the platform, a trusted adult, and possibly authorities', true, 2),
  ('Your digital footprint is…', 'The size of your shoes', false, 1),
  ('Your digital footprint is…', 'The lasting trail of everything you and others post and do online', true, 2),
  ('Your digital footprint is…', 'A type of virus', false, 3),
  ('An old account you forgot about can…', 'Still exist and reveal your data', true, 1),
  ('An old account you forgot about can…', 'Delete itself automatically', false, 2),
  ('An old account you forgot about can…', 'Only be seen by you', false, 3),
  ('Once something is online, it can…', 'Be copied, archived and screenshotted', true, 1),
  ('Once something is online, it can…', 'Never be found again', false, 2),
  ('Once something is online, it can…', 'Only be seen by its owner', false, 3),
  ('Free apps often make money by…', 'Collecting and selling your data', true, 1),
  ('Free apps often make money by…', 'Charging you every day', false, 2),
  ('Free apps often make money by…', 'Mining crypto on your phone', false, 3),
  ('A "personality test" that asks lots of personal questions is…', 'Great fun and totally safe', false, 1),
  ('A "personality test" that asks lots of personal questions is…', 'Often a data-collection trap', true, 2),
  ('A "personality test" that asks lots of personal questions is…', 'Required by law', false, 3),
  ('Third-party cookies are used mainly to…', 'Keep you logged in', false, 1),
  ('Third-party cookies are used mainly to…', 'Track you across websites for advertising', true, 2),
  ('Third-party cookies are used mainly to…', 'Make websites faster', false, 3),
  ('An app wants your contacts but has no reason to. You should…', 'Accept — more permissions is safer', false, 1),
  ('An app wants your contacts but has no reason to. You should…', 'Deny the permission', true, 2),
  ('An app wants your contacts but has no reason to. You should…', 'Ask your contacts first', false, 3),
  ('The best location setting for most apps is…', '"Always"', false, 1),
  ('The best location setting for most apps is…', '"While using" or "ask every time"', true, 2),
  ('The best location setting for most apps is…', '"Never" for everything including maps', false, 3),
  ('Your phone lock screen is important because…', 'It looks cool', false, 1),
  ('Your phone lock screen is important because…', 'Whoever picks up your phone gets your accounts and messages', true, 2),
  ('Your phone lock screen is important because…', 'It saves battery', false, 3),
  ('Software updates mostly exist to…', 'Annoy you', false, 1),
  ('Software updates mostly exist to…', 'Fix security holes that attackers exploit', true, 2),
  ('Software updates mostly exist to…', 'Change the design', false, 3),
  ('A device that no longer receives updates should…', 'Be fine forever', false, 1),
  ('A device that no longer receives updates should…', 'Not be used for important accounts', true, 2),
  ('A device that no longer receives updates should…', 'Be used more', false, 3),
  ('Automatic updates are…', 'A good idea — they patch devices without you remembering', true, 1),
  ('Automatic updates are…', 'A trick to slow your device', false, 2),
  ('Automatic updates are…', 'Illegal in some countries', false, 3),
  ('The safest place to install apps is…', 'A link from a message', false, 1),
  ('The safest place to install apps is…', 'The official app store, checking the developer', true, 2),
  ('The safest place to install apps is…', 'Any website with a download button', false, 3),
  ('An app asking for device-admin or accessibility rights is…', 'Normal for every app', false, 1),
  ('An app asking for device-admin or accessibility rights is…', 'A serious red flag — those powers can read your screen', true, 2),
  ('An app asking for device-admin or accessibility rights is…', 'Proof the app is secure', false, 3),
  ('A game asking for your contacts permission is…', 'Suspicious — games do not need your contacts', true, 1),
  ('A game asking for your contacts permission is…', 'Required to play', false, 2),
  ('A game asking for your contacts permission is…', 'How multiplayer works', false, 3),
  ('A backup protects you from…', 'Device loss, breakage and ransomware', true, 1),
  ('A backup protects you from…', 'Slow internet', false, 2),
  ('A backup protects you from…', 'Battery drain', false, 3),
  ('Before selling a phone you should…', 'Just delete a few photos', false, 1),
  ('Before selling a phone you should…', 'Back up, log out, remove SIM/cards, and factory reset', true, 2),
  ('Before selling a phone you should…', 'Leave it as is — the buyer resets it', false, 3),
  ('A backup you have never tested is…', 'A hope, not a plan', true, 1),
  ('A backup you have never tested is…', 'Perfectly fine', false, 2),
  ('A backup you have never tested is…', 'Better than no backup', false, 3),
  ('Social engineering works by…', 'Manipulating people instead of breaking technology', true, 1),
  ('Social engineering works by…', 'Supercomputers', false, 2),
  ('Social engineering works by…', 'Magic', false, 3),
  ('Ransomware is malware that…', 'Shows you ads', false, 1),
  ('Ransomware is malware that…', 'Locks your files and demands payment', true, 2),
  ('Ransomware is malware that…', 'Steals your friends list', false, 3),
  ('Most malware gets in because…', 'A human lets it in — fake downloads, links or USB sticks', true, 1),
  ('Most malware gets in because…', 'It flies through the Wi-Fi', false, 2),
  ('Most malware gets in because…', 'Phones get it from the factory', false, 3),
  ('Defence in depth means…', 'Layered defences so one failure is not fatal', true, 1),
  ('Defence in depth means…', 'A very deep password', false, 2),
  ('Defence in depth means…', 'Hiding your phone underground', false, 3),
  ('The "human firewall" is…', 'People who recognise and stop social engineering', true, 1),
  ('The "human firewall" is…', 'A special router', false, 2),
  ('The "human firewall" is…', 'A firewall with a face', false, 3),
  ('Which layer protects you if a password leaks?', '2FA — the second factor still stops the attacker', true, 1),
  ('Which layer protects you if a password leaks?', 'A longer username', false, 2),
  ('Which layer protects you if a password leaks?', 'A screen protector', false, 3),
  ('The line between ethical and illegal hacking is…', 'Permission', true, 1),
  ('The line between ethical and illegal hacking is…', 'Age', false, 2),
  ('The line between ethical and illegal hacking is…', 'Skill level', false, 3),
  ('Good places to practise hacking legally are…', 'Your school\'s systems', false, 1),
  ('Good places to practise hacking legally are…', 'Sandboxes like TryHackMe, HackTheBox and picoCTF', true, 2),
  ('Good places to practise hacking legally are…', 'Any website with "test" in the name', false, 3),
  ('Bug bounty programs work by…', 'Companies paying researchers to find and report vulnerabilities', true, 1),
  ('Bug bounty programs work by…', 'Researchers paying companies for access', false, 2),
  ('Bug bounty programs work by…', 'Hunters paying for bugs', false, 3)
) as v(question_text, option_text, is_correct, sort)
join public.quiz_questions qq on qq.question = v.question_text
on conflict do nothing;
