// =============================================================================
// A real PDF text extractor for tests.
//
// This deliberately reads the GENERATED BYTES rather than trusting the code
// that produced them: it inflates every content stream, walks the show-text
// operators in order, and decodes each one two independent ways.
//
//   1. `/ActualText` — the logical Unicode we tag each run with. This is what
//      viewers, copy-paste and accessibility tools use.
//   2. `/ToUnicode`  — the CMap embedded alongside the font subset, mapping the
//      glyph IDs actually drawn back to codepoints. This proves the glyphs
//      exist in the embedded font; if a character had been dropped or replaced
//      by the renderer, it would be missing here.
//
// A PDF that "looks fine" but has no glyphs (the old failure mode) fails both.
// =============================================================================

import zlib from "node:zlib";

type Stream = { dict: string; data: Buffer };

function findStreams(pdf: Buffer): Stream[] {
  const raw = pdf.toString("latin1");
  const streams: Stream[] = [];
  const re = /(\d+)\s+0\s+obj\b([\s\S]*?)\bstream\r?\n/g;
  let match: RegExpExecArray | null;
  while ((match = re.exec(raw))) {
    const dict = match[2];
    const start = match.index + match[0].length;
    const end = raw.indexOf("endstream", start);
    if (end < 0) continue;
    let data = pdf.subarray(start, end);
    // Trim the EOL that precedes `endstream`.
    while (data.length && (data[data.length - 1] === 0x0a || data[data.length - 1] === 0x0d)) {
      data = data.subarray(0, data.length - 1);
    }
    if (/\/FlateDecode/.test(dict)) {
      try {
        data = zlib.inflateSync(data);
      } catch {
        continue;
      }
    }
    streams.push({ dict, data });
  }
  return streams;
}

function hexToUtf16(hex: string): string {
  const clean = hex.replace(/[^0-9a-fA-F]/g, "");
  if (clean.length < 4) return "";
  const bytes = Buffer.from(clean.length % 2 ? `${clean}0` : clean, "hex");
  bytes.swap16();
  let out = bytes.toString("utf16le");
  if (out.charCodeAt(0) === 0xfeff) out = out.slice(1);
  return out;
}

/**
 * Logical text, in reading order, from every `/ActualText` span in the file.
 *
 * This is the extraction path real PDF readers take for shaped scripts, and
 * the one that must return the original Bangla rather than the visually
 * reordered glyph sequence.
 */
export async function extractPdfText(bytes: Uint8Array | Buffer): Promise<string> {
  const pdf = Buffer.isBuffer(bytes) ? bytes : Buffer.from(bytes);
  const parts: string[] = [];
  for (const { dict, data } of findStreams(pdf)) {
    if (/\/Type\s*\/(?:Font|FontDescriptor|XObject)/.test(dict)) continue;
    const content = data.toString("latin1");
    const re = /\/ActualText\s*<([0-9a-fA-F\s]*)>/g;
    let match: RegExpExecArray | null;
    while ((match = re.exec(content))) parts.push(hexToUtf16(match[1]));
  }
  return parts.join("");
}

/**
 * Every codepoint the embedded font subsets can map back from a drawn glyph.
 *
 * Built from the `/ToUnicode` CMaps, so it reflects glyphs that were genuinely
 * embedded and drawn — not just text we asked for.
 */
export function extractDrawnCodepoints(bytes: Uint8Array | Buffer): Set<string> {
  const pdf = Buffer.isBuffer(bytes) ? bytes : Buffer.from(bytes);
  const chars = new Set<string>();
  for (const { data } of findStreams(pdf)) {
    const content = data.toString("latin1");
    if (!content.includes("beginbfchar") && !content.includes("beginbfrange")) continue;
    const add = (hex: string) => {
      for (const ch of hexToUtf16(`feff${hex}`)) chars.add(ch);
    };

    // `<src> <dst>` pairs.
    const bfchar = /beginbfchar([\s\S]*?)endbfchar/g;
    let block: RegExpExecArray | null;
    while ((block = bfchar.exec(content))) {
      const pair = /<([0-9a-fA-F]+)>\s*<([0-9a-fA-F]+)>/g;
      let entry: RegExpExecArray | null;
      while ((entry = pair.exec(block[1]))) add(entry[2]);
    }

    // `<lo> <hi> [<d0> <d1> …]` and `<lo> <hi> <dstStart>` ranges — the form
    // PDFKit actually emits for its font subsets.
    const bfrange = /beginbfrange([\s\S]*?)endbfrange/g;
    while ((block = bfrange.exec(content))) {
      const body = block[1];
      const arrayForm = /<([0-9a-fA-F]+)>\s*<([0-9a-fA-F]+)>\s*\[([^\]]*)\]/g;
      let entry: RegExpExecArray | null;
      const consumed: Array<[number, number]> = [];
      while ((entry = arrayForm.exec(body))) {
        consumed.push([entry.index, entry.index + entry[0].length]);
        const dst = /<([0-9a-fA-F]+)>/g;
        let item: RegExpExecArray | null;
        while ((item = dst.exec(entry[3]))) add(item[1]);
      }
      const simpleForm = /<([0-9a-fA-F]+)>\s*<([0-9a-fA-F]+)>\s*<([0-9a-fA-F]+)>/g;
      while ((entry = simpleForm.exec(body))) {
        if (consumed.some(([start, end]) => entry!.index >= start && entry!.index < end)) continue;
        const lo = parseInt(entry[1], 16);
        const hi = parseInt(entry[2], 16);
        const dst = parseInt(entry[3], 16);
        for (let i = 0; i <= hi - lo && i < 0x10000; i++) add((dst + i).toString(16).padStart(4, "0"));
      }
    }
  }
  return chars;
}

/** Number of pages declared by the document. */
export function pageCount(bytes: Uint8Array | Buffer): number {
  const raw = Buffer.from(bytes).toString("latin1");
  const counts = [...raw.matchAll(/\/Type\s*\/Pages[\s\S]{0,200}?\/Count\s+(\d+)/g)].map((m) => Number(m[1]));
  if (counts.length) return Math.max(...counts);
  return (raw.match(/\/Type\s*\/Page[^s]/g) ?? []).length;
}

/** Declared page dimensions, in points. */
export function mediaBoxes(bytes: Uint8Array | Buffer): Array<[number, number]> {
  const raw = Buffer.from(bytes).toString("latin1");
  return [...raw.matchAll(/\/MediaBox\s*\[\s*[\d.]+\s+[\d.]+\s+([\d.]+)\s+([\d.]+)\s*\]/g)].map(
    (m) => [Number(m[1]), Number(m[2])] as [number, number],
  );
}
